import { getStudentMLPrediction } from '../services/mlService.js';
import { supabaseAdmin } from '../config/supabase.js';

const ML_SERVICE_URL = 'http://localhost:8000';

async function runPhase7MLTests() {
  console.log('\n==================================================');
  console.log('CAREERPILOT AI - PHASE 7 ML PIPELINE & XAI TEST');
  console.log('==================================================\n');

  let passed = 0;
  let failed = 0;

  function assert(cond, name, details = '') {
    if (cond) {
      console.log(`[PASS] ${name} ${details ? '(' + details + ')' : ''}`);
      passed++;
    } else {
      console.error(`[FAIL] ${name} ${details ? '(' + details + ')' : ''}`);
      failed++;
    }
  }

  // 1. Direct Python FastAPI Microservice Test
  console.log('--- 1. Testing Python FastAPI Microservice (/predict) ---');
  try {
    const pyPayload = {
      cgpa: 8.7,
      semester: 6,
      graduation_year: 2026,
      skills_count: 7,
      projects_count: 3,
      certificates_count: 2,
      internships_count: 1,
      readiness_score: 82,
      branch: 'Computer Science',
      academic_year: '3rd Year'
    };

    const pyRes = await fetch(`${ML_SERVICE_URL}/predict`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(pyPayload)
    });

    if (pyRes.ok) {
      const data = await pyRes.json();
      assert(data.success === true, 'Python FastAPI /predict returns success: true', `Model: ${data.selected_model}`);
      assert(typeof data.probability === 'number' && data.probability >= 0 && data.probability <= 1, 'Python model produces probability in [0, 1]', `Prob: ${data.probability} (${data.probability_percentage}%)`);
      assert(['High Readiness', 'Moderate Readiness', 'Needs Skill Enhancement'].includes(data.status), 'Python service returns valid readiness status', `Status: ${data.status}`);
      assert(data.explanation && (data.explanation.positive_factors || data.explanation.improvement_areas), 'Python service returns model-driven XAI explanation object');
    } else {
      assert(false, 'Python FastAPI /predict endpoint reachable', `HTTP ${pyRes.status}`);
    }
  } catch (err) {
    console.warn('[INFO] Python microservice offline during test, testing Node fallback pipeline:', err.message);
  }

  // 2. Test Invalid/Missing Input Handling (Requirement 10 & 32)
  console.log('\n--- 2. Testing Missing Feature & Invalid Input Handling ---');
  const missingDataResult = await getStudentMLPrediction('00000000-0000-0000-0000-000000000000');
  assert(
    missingDataResult.status === 'insufficient_data',
    'Missing profile features return status: insufficient_data',
    `Status: ${missingDataResult.status}`
  );
  assert(
    Array.isArray(missingDataResult.missing_fields) && missingDataResult.missing_fields.length > 0,
    'Explicit missing_fields array returned',
    `Missing: ${missingDataResult.missing_fields?.join(', ')}`
  );

  // 3. Test Node.js Service with Fallback / Embedded ML Pipeline
  console.log('\n--- 3. Testing Node.js mlService Integration ---');
  const dummyStudentId = '11111111-1111-1111-1111-111111111111';
  
  // Create an authentic student profile in mock metadata/database test flow
  const mockFeaturePayload = {
    cgpa: 8.5,
    semester: 7,
    graduation_year: 2026,
    skills_count: 6,
    projects_count: 2,
    certificates_count: 1,
    internships_count: 1,
    readiness_score: 78,
    branch: 'Computer Science',
    academic_year: '4th Year'
  };

  try {
    const resJson = await getStudentMLPrediction(dummyStudentId, mockFeaturePayload);
    assert(resJson.success === true, 'End-to-End ML Feature Pipeline execution succeeds', `Prob: ${resJson.probability_percentage}%`);
    assert(resJson.predicted_class === 1 || resJson.predicted_class === 0, 'Class prediction generated by model', `Class: ${resJson.predicted_class} (${resJson.prediction})`);
    assert(resJson.explanation?.positive_factors?.length > 0, 'XAI positive contributing factors identified from model', `Count: ${resJson.explanation?.positive_factors?.length}`);
    assert(resJson.explanation?.improvement_areas?.length > 0, 'XAI improvement areas identified from model', `Count: ${resJson.explanation?.improvement_areas?.length}`);
  } catch (e) {
    assert(false, 'End-to-End ML Pipeline execution', e.message);
  }

  // 4. Test Frontend Build Verification
  console.log('\n==================================================');
  console.log(`Phase 7 Test Execution Complete: ${passed} PASSED, ${failed} FAILED`);
  console.log('==================================================\n');

  if (failed > 0) {
    process.exit(1);
  }
}

runPhase7MLTests();
